version: "3"

services:
  server:
    platform: linux/x86_64
    container_name: server
    build:
      context: ./server
    stdin_open: true
    tty: true
    working_dir: /src
    ports:
      - "8000:8000"
    volumes:
      - ./server:/src
    env_file:
      - .env.dev
    command: >
      sh -c "sh migrations.sh && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
      - redis

  client:
    container_name: client
    build: ./client
    stdin_open: true
    tty: true
    working_dir: /src
    ports:
      - "3000:3000"
    volumes:
      - ./client:/src
    env_file:
      - .env.dev
    command: >
      sh -c "npm install -g npm@latest && npm install && npm run dev"
    depends_on:
      - server
      - db

  db:
    container_name: db
    image: postgres
    env_file:
      - .env.dev

  redis:
    container_name: redis
    image: redis:7.0-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --save 20 1 --loglevel warning --requirepass gLMgr@9DAy77UE4
    restart: always

volumes:
  redis_data:
