version: "3"

services:
  server:
    platform: linux/x86_64
    container_name: server
    build:
      context: ./server
    stdin_open: true
    tty: true
    working_dir: /src
    ports:
      - "8000:8000"
    volumes:
      - ./server:/src
    env_file:
      - .env.dev
    environment:
      - DJANGO_SETTINGS_MODULE=server.settings
      - PYTHONPATH=/src
      - REDIS_HOST=redis
    command: >
      sh -c "sh migrations.sh && uvicorn server.asgi:application --host 0.0.0.0 --port 8000 --reload"
    depends_on:
      - db
      - redis

  client:
    container_name: client
    build: ./client
    stdin_open: true
    tty: true
    working_dir: /src
    ports:
      - "3000:3000"
    volumes:
      - ./client:/src
      - /src/node_modules
    env_file:
      - .env.dev
    command: npm run dev
    depends_on:
      - server
      - db

  db:
    container_name: db
    image: postgres
    env_file:
      - .env.dev
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  postgres_data:
