version: "3"

services:
  server:
    platform: linux/x86_64
    container_name: server
    build:
      context: ./server
    stdin_open: true
    tty: true
    working_dir: /src
    ports:
      - "8000:8000"
    volumes:
      - ./server:/src
    env_file:
      - .env.dev
    environment:
      - DJANGO_SETTINGS_MODULE=server.settings
      - PYTHONPATH=/src
      - REDIS_HOST=redis
    command: >
      sh -c "sh migrations.sh && uvicorn server.asgi:application --host 0.0.0.0 --port 8000 --reload"
    depends_on:
      - db
      - redis

  client:
    container_name: client
    build:
      context: ./client
      target: development
    platform: linux/x86_64
    stdin_open: true
    tty: true
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./client/components:/app/components
      - ./client/lib:/app/lib
      - ./client/pages:/app/pages
      - ./client/styles:/app/styles
      - ./client/types:/app/types
      - ./client/hooks:/app/hooks
      - ./client/scripts:/app/scripts
      - ./client/public:/app/public
      - ./client/themes:/app/themes
      - ./client/contexts:/app/contexts
      - ./client/utils:/app/utils
      - ./client/tests:/app/tests
      - ./client/jest.config.js:/app/jest.config.js
      - ./client/jest.setup.js:/app/jest.setup.js
      - /app/node_modules
      - /app/.next
    env_file:
      - .env.dev
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
      - WATCHPACK_POLLING=true
      - SHELL=/bin/zsh
    command: npm run dev
    depends_on:
      - server
      - db

  db:
    container_name: db
    image: postgres
    env_file:
      - .env.dev
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  postgres_data:
